name: Post-deployment Validations

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      BASE_URL:
        type: string
        required: true
      COGNITO_USER_POOL_ID:
        type: string
        required: true
      USERNAME:
        type: string
        required: true

jobs:
  create-test-user:
    name: Create Test User
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:



  test-api:
    name: Run Portman With USER_PASSWORD_AUTH
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
          role-session-name: create-test-user
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Create Test User
        run: |
          echo "USERNAME=$(uuidgen)@andmore.dev" >> $GITHUB_ENV;
          echo "PASSWORD=$(uuidgen)" >> $GITHUB_ENV;
          aws cognito-idp admin-create-user --user-pool-id ${{ inputs.COGNITO_USER_POOL_ID }} --username $USERNAME
          aws cognito-idp admin-set-user-password --user-pool-id ${{ inputs.COGNITO_USER_POOL_ID }} --username $USERNAME --password $PASSWORD --permanent
          # aws cognito-idp admin-delete-user --user-pool-id ${{ inputs.COGNITO_USER_POOL_ID }} --username $USERNAME


      - name: Test API
        env:
          COGNITO_URL: ${{ secrets.COGNITO_URL }}
          CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          # USERNAME: ${{ secrets.COGNITO_USERNAME }}
          # PASSWORD: ${{ secrets.COGNITO_PASSWORD }}
        run: |
          npm ci

          node ./portman/get-auth-token/user-password-auth.mjs
          npx @apideck/portman --cliOptionsFile portman/portman-cli.json --baseUrl ${{ inputs.BASE_URL }}
